apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cicd-app
  labels:
    app: java-cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cicd-app
  template:
    metadata:
      labels:
        app: java-cicd-app
    spec:
      containers:
      - name: java-cicd-app
        image: docker.io/vinayreddy18/java-cicd-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
