apiVersion: v1
kind: Service
metadata:
  name: java-cicd-service
spec:
  type: LoadBalancer # Use NodePort if LoadBalancer is not supported by local k8s setup
  selector:
    app: java-cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
